// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATFGmvGsAhZH9UH00ubenavgQw1KhBv2Y',
    appId: '1:1010336660025:android:c66b3e9120acb8e64febe8',
    messagingSenderId: '1010336660025',
    projectId: 'chatty-49ae5',
    storageBucket: 'chatty-49ae5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKtyDgeWLPv5crw93oQMgLjoa9nQqHCfI',
    appId: '1:1010336660025:ios:93587cc58848604a4febe8',
    messagingSenderId: '1010336660025',
    projectId: 'chatty-49ae5',
    storageBucket: 'chatty-49ae5.appspot.com',
    androidClientId: '1010336660025-p7sfguarqbacbp1dq03k2vrve463n8op.apps.googleusercontent.com',
    iosClientId: '1010336660025-j0d1u2jql3uevacchq5i7auvvklua7ic.apps.googleusercontent.com',
    iosBundleId: 'com.devans.chatty',
  );
}
